---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - update-types: ["version-update:semver-patch"]
        dependency-name: "*"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - update-types: ["version-update:semver-patch"]
        dependency-name: "*"
